### PR TITLE
Update to work with test groups

### PR DESCRIPTION
**Pull request by ana**
This will allow the frontend to show every test group and their
included test cases. However it will need further updating
to show the subgroups included in the test group (if any).

There are two changes:
* rename from suite to group
* use test_cases instead of test_case since the field was renamed
in the backend

Signed-off-by: Ana Guerrero Lopez <ana.guerrero@collabora.com>

### CODE REVIEW

**Comment by ana** [comment]
This is required tfor the frontend to work after the changes in https://github.com/kernelci/kernelci-backend/pull/77

**Comment by gctucker** [comment]
Tested OK on staging, here's an example:
https://staging.kernelci.org/test/group/5b9ae74dcf3a0f7f02626a1f/
(Note: It's required to clear browser caches with this wip version otherwise the new JS won't load and an error will be displayed)

**Comment by MiloCasagrande** [comment]
All looks good!

If you want to avoid the force-refresh, you should bump the "date" part of the JavaScript files (and update `common.js` and `build.js` as well) to something like `2018.09`.

**Review by MiloCasagrande — APPROVED** [review]

**Comment by gctucker** [comment]
Thanks @MiloCasagrande, yes we should do that before rolling it out in production.  The issue with staging is that we may iterate through changes several times and renaming the files each time is a bit tedious.

**Review by gctucker — APPROVED** [review]

**Comment by ana** [comment]
Added new commit to bump all the changed files and the app version to 2018.9

**Review by gctucker — APPROVED** [review]

**Comment by khilman** [comment]
> Tested OK on staging, here's an example:
> https://staging.kernelci.org/test/group/5b9ae74dcf3a0f7f02626a1f/
> (Note: It's required to clear browser caches with this wip version otherwise the new JS won't load and an error will be displayed)

Minor nit: in clicking through the new view, there's one more mention of "Total test sets" e.g.: https://staging.kernelci.org/test/board/rk3288-veyron-jaq/job/gtucker/kernel/kernelci-test-079-7-gdc7319aa62b8/

**Comment by ana** [comment]
> Minor nit: in clicking through the new view, there's one more mention of "Total test sets" e.g.: https://staging.kernelci.org/test/board/rk3288-veyron-jaq/job/gtucker/kernel/kernelci-test-079-7-gdc7319aa62b8/

Yeah, I left that with the intention of renaming it to "Total test groups". I intent to send a follow-up with that but it's not a top priority.

**Comment by gctucker** [comment]
It's probably worth removing that column as it's not useful now.  When we want to have a web UI capable of showing any number of nested sub-groups then we may do something completely different.

**Comment by ana** [comment]
> It's probably worth removing that column as it's not useful now. When we want to have a web UI capable of showing any number of nested sub-groups then we may do something completely different.

You think so? I think it's worthwhile for knowing there are more groups there that are not shown.

**Comment by gctucker** [comment]
Would you show only the number of sub-groups at the first level (like test sets), or recursively go through all the sub-groups in sub-groups to make up that total?

My point is that only showing the number of sub-groups at the first level isn't quite a complete implementation, so it might be better to not have it at all.  Also just showing the number of groups without the actual test case results inside them may not be too useful.

A simple way to fix this in the short term could be to follow the same approach as on the LAVA web UI, with the name of the test set in the column:
https://lava.collabora.co.uk/results/1276275/0_simple

That wouldn't scale too well with groups-in-groups as joining the group names together can get very long (`networking/foo/bar` or `networking.foo.bar`...), which is why it would be a short-term solution as we don't have test plans with that number of sub-groups.

**Comment by khilman** [comment]
I have slight preference for leaving it, since that's how it's been until today.  I agree that it wont handle recursive nesting, but that's fine for now.  I think the next step is coming up with completely new views for the test data as what we have today is only focused on a specific board.

**Pull request merged**
