### PR TITLE
T18943 delete test board view

### PR DESCRIPTION
**Pull request by alexandrasp**
Now that kci has changed tests view, all views related to filter or show tests by board
will be removed. For this PR we remove the view that shows tests by board.

Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>

### CODE REVIEW

**Comment by alexandrasp** [comment]
Tested OK on staging https://staging.kernelci.org/test/board/bcm2837-rpi-3-b/ 
https://staging.kernelci.org/test/board/alpine-db/

**Comment by gctucker** [comment]
> Tested OK on staging https://staging.kernelci.org/test/board/bcm2837-rpi-3-b/
> https://staging.kernelci.org/test/board/alpine-db/

These views are gone, but we need to check nothing was broken on the other views too.

**Comment by alexandrasp** [comment]
> > Tested OK on staging https://staging.kernelci.org/test/board/bcm2837-rpi-3-b/
> > https://staging.kernelci.org/test/board/alpine-db/
> 
> These views are gone, but we need to check nothing was broken on the other views too.

yes! I see, other views have chance to cause more impact..because there are more link to them.

**Comment by gctucker** [comment]
No issues found on the new views as a side-effect of this PR.

**Pull request merged**
