### PR TITLE
Change "Compiler" column to "Build Environment"

### PR DESCRIPTION
**Pull request by chaws**
and add "Build Environment" to boots page as well.

This depends on https://github.com/kernelci/kernelci-core-staging/pull/66 and https://github.com/kernelci/kernelci-backend/pull/86

### CODE REVIEW

**Comment by mattface** [comment]
Hey Charles, this is the patch I've been carrying on my local frontend development setup
https://github.com/mattface/kernelci-frontend/tree/build-environment
It's very similar but I've also removed the compiler fields when viewing a single boot and added the environment. The same should really be done for viewing a single build as well.

**Comment by chaws** [comment]
Hi Matt, just pushed an update. Both boots/builds listings and details pages had `compiler` replaced by `build environment`. I think now it's good to go

**Comment by gctucker** [comment]
Tested OK on staging:
https://staging.kernelci.org/build/id/5cf98e2fcf3a0f8ce8fff719/
https://staging.kernelci.org/boot/id/5cf9955ecf3a0f8cebfff6ea/

**Comment by gctucker** [comment]
@chaws actually it seems to be working for detailed views but not for listings, could you please check on https://staging.kernelci.org if this is as expected?

**Comment by gctucker** [comment]
@chaws Ah, sorry I see it now:
https://staging.kernelci.org/build/

Is it really better? I find it long and confusing as a title, Compiler was fine imo.  The "build environment" denomination is more of an implementation detail I think.

**Comment by chaws** [comment]
@gctucker , I agree, at that time I thought some more information besides the compiler could be displayed in that column. Also, it forced some lab names to break to the second line, making it ugly. Let me update that.

**Comment by gctucker** [comment]
This is not relevant any more.

**Pull request closed without merging**
