### PR TITLE
T18943 delete tests board job

### PR DESCRIPTION
**Pull request by alexandrasp**
This removes files that were left to be removed from view that shows tests-board-job.

### CODE REVIEW

**Comment by alexandrasp** [comment]
Tested OK on staging: https://staging.kernelci.org/test/board/alpine-db

**Review by gctucker — CHANGES_REQUESTED** [review]
Please take a look at the diff.

**Comment by alexandrasp** [comment]
> Please take a look at the diff.

Fixed :innocent:

**Comment by gctucker** [comment]
Well, please rebase again now that #93 has been merged.

**Comment by gctucker** [comment]
Thanks, this should get merged tomorrow if it seems all fine after the next staging update.

**Review by gctucker — APPROVED** [review]

**Pull request merged**
