### PR TITLE
Update keyboard shortcuts

### PR DESCRIPTION
**Pull request by alexandrasp**

### CODE REVIEW

**Comment by alexandrasp** [comment]
Tested OK on staging.
Boot icons removed, key shortcut is back on info page and test page now has its own key shortcut (g+t) .

**Comment by gctucker** [comment]
It's causing some views to not work, for example this one is not loading any test results:
https://staging.kernelci.org/test/job/next/branch/master/kernel/next-20210322/plan/baseline/

It works again with this PR skipped.  Please test it locally to debug the issue.

**Comment by gctucker** [comment]
Still causing the same issue: https://staging.kernelci.org/test/job/kernelci/branch/staging-stable/kernel/staging-stable-20210518.0/plan/baseline/

Adding skip tag for now.

**Comment by gctucker** [comment]
@alexandrasp This is still causing some issues on the page with the test plan results.

**Comment by alexandrasp** [comment]
@gctucker finally is working. Could take a look ? So I can merge this PR.

**Comment by gctucker** [comment]
@alexandrasp No it's not, this page keeps spinning for ever: https://staging.kernelci.org/test/plan/id/60c30893aa0897fc72c6cbed/

Again, have you actually reproduced the issue locally and made a fix?  And if so, what was the fix?

I need to put the `staging-skip` label again as we can't see results on the staging frontend otherwise.

**Comment by gctucker** [comment]
OK sorry it seems to be working now, I've removed the skip label again.  I think there was a problem just with the page I was looking at.

Still, what was the issue?

**Comment by gctucker** [comment]
There's also an issue here, even with this PR skipped (so it's another kind of issue):
https://staging.kernelci.org/test/plan/id/60c32001c97befa838c6cc0c/

**Review by gctucker — APPROVED** [review]
Tested OK on staging.

**Pull request merged**
