### PR TITLE
[wip] rebase AGL front-end changes on top of master branch

### PR DESCRIPTION
**Pull request by alexandrasp**

### CODE REVIEW

**Comment by gctucker** [comment]
@alexandrasp Please let us know when this PR should be good enough to be enabled on staging.kernelci.org.

The objective of this PR I think is to have the new tests view from AGL added to the frontend.  Then we can look into consolidating things: removing broken Tests view, improving new Tests view from AGL to make it good enough to replace the Boots view...

**Comment by gctucker** [comment]
The main jobs view seems to be broken with this PR: https://staging.kernelci.org/job/

The numbers never show up, it looks like no requests are being sent to the backend to get the build and boot counts.

The detailed build and boot views seem to work as expected though:
https://staging.kernelci.org/build/kernelci/branch/staging.kernelci.org/kernel/staging-20191113.0/

**Comment by alexandrasp** [comment]
ty @gctucker. I am working to fix it and tests by build.

**Comment by alexandrasp** [comment]
@gctucker in the case of jobs' page, infinite loading is caused by batch without an expected return and the same problem is happening in the case of tests by build trying to perform a batch in `test_case` table.

**Comment by gctucker** [comment]
The issue on the jobs page goes away without this PR.  Please try to reproduce and fix locally then update it.  Having this issue on staging can mask other problems with frontend/backend interactions which is especially important to track since the Mongo DB / PyMongo upgrade.

**Comment by alexandrasp** [comment]
I will close this PR in order to rebase and open new PRs step by step of AGL feature/patches to master.

**Pull request closed without merging**
