### PR TITLE
tests by build - show builds

### PR DESCRIPTION
**Pull request by alexandrasp**
Update changes from AGL branch in order to
show builds and some build details correctly.

Signed-off-by: Oussema DAOUD <odaoud@baylibre.com>
Signed-off-by: Alexandra Pereira <alexandra.pereira@collabora.com>

### CODE REVIEW

**Comment by alexandrasp** [comment]
@gctucker it includes a view with build infos. Let me know if it is all right to proceed to the next page, show all groups from a build. It can be tested on staging, but I am thinking about remove all code that is from `tested by build` feature from AGL and it is not properly used at this moment.

**Comment by gctucker** [comment]
https://staging.kernelci.org/test-build/ shows 404 error from backend

**Comment by gctucker** [comment]
The error is:
```
Dec 31 09:32:21 ip-172-30-0-172 kernelci-backend[24292]: [ WARNING/MainThread] 404 GET /suite/distinct/kernel?aggregate=job&date_range=14&sort_order=-1&sort=created_on (127.0.0.1) 0.53ms
```
which is expected because the `suite` API entry point has been replaced with `group`.

**Comment by alexandrasp** [comment]
> The error is:
> 
> ```
> Dec 31 09:32:21 ip-172-30-0-172 kernelci-backend[24292]: [ WARNING/MainThread] 404 GET /suite/distinct/kernel?aggregate=job&date_range=14&sort_order=-1&sort=created_on (127.0.0.1) 0.53ms
> ```
> 
> which is expected because the `suite` API entry point has been replaced with `group`.

oh, it was my fault, sorry! I just update this branch, I am working on the next view, that will show all groups from one build.

**Comment by gctucker** [comment]
OK thanks, I'll update the live staging branch a bit later today with the latest changes from this PR.

**Comment by alexandrasp** [comment]
> OK thanks, I'll update the live staging branch a bit later today with the latest changes from this PR.

good! I am following the concept to put all views to work first, after we can adapt it, put more details, or remove, etc.

**Comment by gctucker** [comment]
Just updated staging - WIP test-by-build view available here: https://staging.kernelci.org/test-build/

**Comment by alexandrasp** [comment]
@gctucker less 1500 lines!

**Comment by khilman** [comment]
FYI... the current /tests-build view on staging never loads any data and causes my browser to start consuming 100% CPU

**Comment by alexandrasp** [comment]
> FYI... the current /tests-build view on staging never loads any data and causes my browser to start consuming 100% CPU

ok @khilman, thank you  for your comment, I will check. Not sure if this code is already automatically deployed.

**Comment by gctucker** [comment]
If it doesn't have the `staging-skip` label and it doesn't conflict with other PRs then it gets deployed every time there's a new run on staging.

**Comment by gctucker** [comment]
You can check the `staging.kernelci.org` branch to see what is deployed.

**Pull request closed without merging**
