### PR TITLE
Syntax clean-up of view-tests-*.js files

### PR DESCRIPTION
**Pull request by gctucker**
Some global syntax clean-up in the view-tests-*.js files:

* add missing semicolons
* remove some unused variables
* use `URI.buildQuery()`
* use inline functions in `.forEach()` iterations

### CODE REVIEW

**Comment by alexandrasp** [comment]
@gctucker did you use any linter?

**Comment by gctucker** [comment]
> @gctucker did you use any linter?

I wasn't initially but now I'm using `eslint` with the `semi` rule turned on.

**Review by alexandrasp — APPROVED** [review]
LGTM

**Comment by gctucker** [comment]
Tested OK on staging.

**Pull request merged**
