### PR TITLE
Remove build/test rates graphs  

### PR DESCRIPTION
**Pull request by alexandrasp**
Remove js script that was used by testrate and buildrate graphs in the job/<tree>/ and job/<tree>/<branch> views.

### CODE REVIEW

**Comment by alexandrasp** [comment]
I am investigating side effects of removing pass and test rate code..some pages are failing to load data yet.

**Comment by gctucker** [comment]
Can you reproduce the issue with your local instance?

**Comment by alexandrasp** [comment]
> Can you reproduce the issue with your local instance?

yes, I can! And I pushed a minor fix, not sure if it was sent to staging..

**Comment by gctucker** [comment]
There's an issue with Ansible failing on staging right now, once that's fixed it should get deployed.

**Comment by alexandrasp** [comment]
tested OK in staging: 

https://staging.kernelci.org/job/kernelci/ 
https://staging.kernelci.org/job/kernelci/branch/staging-stable/

Build and Test Pass Rate are not available anymore.

**Review by gctucker — APPROVED** [review]
Looks like there's no side-effects so it's all good.

**Pull request merged**
